title: /home/ta8ozh
author: C. O.
description: I'm not someone significant enough for a story to be written about me (yet).
keywords: aviation, fpv, photography, programing, ham radio, linux
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ta8ozh.github.io"

#social links
bluesky: ta8ozh.bsky.social
twitter: ta8ozh
github: ta8ozh
linkedin: canerozhan
#email: test@test.com
